unique_ids:
  forms:
    Form1: YHOOBJCXTUDFMV4Z3F3HZ64GUXM7RL2R
  modules: {}
  server_modules: {}
  assets:
    theme.css: YVUYJMTSJM7SUSDKQE42DNKNNYK3CUGY
    standard-page.html: Y4ORH3G5Z7NFKLY6CFWIOQF4KYBOMYBZ
  scripts: {}
