unique_ids:
  forms:
    Form1: YHOOBJCXTUDFMV4Z3F3HZ64GUXM7RL2R
  modules: {}
  server_modules:
    ServerModule1: '1724002984360765930914090.0219'
  assets:
    standard-page.html: Y4ORH3G5Z7NFKLY6CFWIOQF4KYBOMYBZ
    theme.css: YVUYJMTSJM7SUSDKQE42DNKNNYK3CUGY
  scripts: {}
